Kitchen2 disabled products
yamfood/yamadmin pull request #47
Opened 2020-04-04 15:42 UTC by Bekhzod1995

2020-04-04 15:51 UTC, kensay98 requested changes

2020-04-04 15:51 UTC, kensay98 commented on src/components/KitchenDisabledProducts.js
> +    <>
?

2020-04-04 15:51 UTC, kensay98 commented on src/components/KitchenDisabledModal.js
> +  const handleCanel = () => {
typo

2020-04-04 19:41 UTC, igakim requested changes

2020-04-04 19:41 UTC, igakim commented on src/components/KitchenDisabledModal.js
> +  const products = useSelector((state) => state.kitchens);
СТрока максимально непонятная. ты забираешь из стейта `kitchens` и записываешь в `products`?

2020-04-04 19:41 UTC, igakim commented on src/components/KitchenDisabledModal.js
> +  const { productsModal } = products;
Из продуктов ты забираешь модалку?

2020-04-04 19:41 UTC, igakim commented on src/components/KitchenDisabledModal.js
> +  const [productsList, setProducts] = useState(productsModal);
В целом, ты намешал логику стейта из редакса и локального стейта. Разбираться что откуда и куда очень сложно. Нужно пофиксить иначе это не поддерживаемо. Если ты используешь Редакс то в локальном стейте ты не должен нуждаться.

2020-04-04 19:41 UTC, igakim commented on src/components/KitchenDisabledModal.js
> +                  >
У тебя есть css-loader в вебпаке? Вообще css файлы есть?. Когда так много стилей к одному компоненту - лучше вынести куда-нибудь. Хотя бы в отдельный объект (`Object`)

2020-04-04 19:41 UTC, igakim commented on src/components/KitchenDisabledModal.js
> +                </Button>
Поставь на кнопку `loading` чтобы пользователь понимал что идет загрузка - здесь это важно

2020-04-04 19:41 UTC, igakim commented on src/components/OrderDetails.js
> +    };
Такие дела лучше делать через диспетчеризацию по типу. Почитай как будет время что это такое. Точно также как ты в apiRoutes.js используешь роуты. 

```
const tagsMap = {
  new: <Tag>Новый</Tag>,
  onWay: <Tag>В пути</Tag>,
}
```

2020-04-04 19:41 UTC, igakim commented on src/components/OrderDetails.js
> +                return <Tag color="#108ee9">Новый</Tag>;
Что с отступами??????????????

2020-04-04 19:41 UTC, igakim commented on src/components/OrderDetails.js
> +            <h3><strong>Продукты</strong></h3>
Отступы

2020-04-05 07:19 UTC, kensay98 commented on src/components/OrderDetails.js
> +    };
Это мое)))

2020-04-05 07:20 UTC, kensay98 commented on src/components/OrderDetails.js
> +                return <Tag color="#108ee9">Новый</Tag>;
это тоже

2020-04-05 13:07 UTC, Bekhzod1995 commented on src/components/OrderDetails.js
> +            <h3><strong>Продукты</strong></h3>
это тоже Рустама. Эти файлы пока я трогать не буду, когда Рустам даст задания тогда изменю

2020-04-05 13:08 UTC, Bekhzod1995 commented on src/components/KitchenDisabledModal.js
> +                  >
это create-react-app. Окай так и сделаю

2020-04-05 13:12 UTC, Bekhzod1995 commented on src/components/KitchenDisabledModal.js
> +  const [productsList, setProducts] = useState(productsModal);
это же search продуктов в модалке. Окай пофиксу

2020-04-05 13:14 UTC, Bekhzod1995 commented on src/components/KitchenDisabledModal.js
> +  const handleCanel = () => {
typo?

2020-04-05 13:14 UTC, Bekhzod1995 commented on src/components/KitchenDisabledProducts.js
> +    <>
ты про <>  </> ?

2020-04-05 13:18 UTC, kensay98 commented on src/components/KitchenDisabledModal.js
> +  const handleCanel = () => {
Опечатка в слове Canel

2020-04-05 13:18 UTC, kensay98 commented on src/components/KitchenDisabledProducts.js
> +    <>
да

2020-04-05 13:21 UTC, igakim commented on src/components/KitchenDisabledModal.js
> +  const [productsList, setProducts] = useState(productsModal);
И что что search в  модалке? По коду как понять? Я тебе дал пример работы на codepen, а не сам код. А ты тупо скопировал.

2020-04-05 13:50 UTC, Bekhzod1995 commented on src/components/KitchenDisabledModal.js
> +  const [productsList, setProducts] = useState(productsModal);
Окай Сорри

2020-04-05 13:50 UTC, Bekhzod1995 commented on src/components/KitchenDisabledModal.js
> +  const handleCanel = () => {
а сорри

2020-04-05 13:53 UTC, Bekhzod1995 commented on src/components/KitchenDisabledProducts.js
> +    <>
В начале я на возвращал 2 компонента поэтому использовал, забыл убрать.

2020-04-06 16:35 UTC, igakim approved these changes

2020-04-06 16:35 UTC, merged