Image upload
yamfood/yamadmin pull request #52
Opened 2020-04-12 20:47 UTC by Bekhzod1995

2020-04-12 20:55 UTC, kensay98 commented on src/apiRoutes.js
> +  uploadFile: (file) => [host, `sign-s3?folder=test&file-name=${file.name}`].join('/'),
это не урл не для uploadFile, а для получения signedRequest, назови getSignedRequest

2020-04-12 20:55 UTC, kensay98 commented on src/actions/index.js
> +    message.error('Ошибка при добавлении', 3);
Сделай текст актуальный, пиши что это ошибка при загрузке файла

2020-04-12 20:55 UTC, kensay98 commented on src/actions/index.js
> +    message.error('Ошибка при добавлении', 3);
тут пиши "Ошибка во время подготовки запроса на загрузку"

2020-04-13 06:08 UTC, igakim requested changes

2020-04-13 06:08 UTC, igakim commented on src/actions/index.js
> +    }
Проверка зачем? Спорим ты даже не понимаешь сам зачем эта проверка?

2020-04-13 06:08 UTC, igakim commented on src/apiRoutes.js
> +  uploadFile: (file) => [host, `sign-s3?folder=test&file-name=${file.name}`].join('/'),
Тысяча пятьсот миллион двадцать пятый раз говорю. QUERYSTRING здесь не указывается

2020-04-13 06:08 UTC, igakim commented on src/components/FileUploader.js
> +  };
Бесполезная проверка. Во-первых, сравнивать нужно всегда и везде строго `===`. Во-вторых, если file === null, выведется сообщение и все равно пойдет диспатч экшена. Возврат `null` - для чего?

2020-04-13 06:08 UTC, igakim commented on src/components/FileUploader.js
> +  );
Почему не взял файлпикер ант дизайна?

2020-04-17 08:31 UTC, closed without merging